(define (domain towerofhanoi)
	(:predicates
		(clear ?a)
		(smaller ?a ?b)
		(on ?a ?b)
	(:action movedisk :parameters (?disk ?from ?to)
		 :precondition (and (clear ?disk)
		 	       	    (smaller ?disk ?to)
			       	    (on ?disk ?from)
			       	    (clear ?to))
		 :effect (and (on ?disk ?to)
		 	      (clear ?from)
			      (not (on ?disk ?from))
			      (not (clear ?to))))))