(define (problem threepegsfourdisks)
	(:domain towerofhanoi)
	(:objects peg1 peg2 peg3 disk1 disk2 disk3 disk4)
	(:init (on disk1 peg1)
	       (on disk2 disk1)
	       (on disk3 disk2)
	       (on disk4 disk3)
	       (clear disk4)
	       (clear peg2)
	       (clear peg3)
	       (smaller disk4 disk3)
	       (smaller disk4 disk2)
	       (smaller disk4 disk1)
	       (smaller disk3 disk2)
	       (smaller disk3 disk1)
	       (smaller disk2 disk1)
	       (smaller disk1 peg1) (smaller disk1 peg2) (smaller disk1 peg3)
	       (smaller disk2 peg1) (smaller disk2 peg2) (smaller disk2 peg3)
	       (smaller disk3 peg1) (smaller disk3 peg2) (smaller disk3 peg3)
	       (smaller disk4 peg1) (smaller disk4 peg2) (smaller disk4 peg3))
	       (:goal (and (on disk4 disk3)
	       	      (on disk3 disk2)
	       	      (on disk2 disk1)
		      (on disk1 peg3))))
		      